# NumPy

### Lesson 1: The `ndarray`

ndarray stands for N-Dimensional Array. where N is a positive Integer.

In [3]:
import numpy as np # importing the numpy module.
from mpmath import eye

In [3]:
# creating the first array.
marks = np.array([10, 20, 30])
type(marks) # Observation: the data type is not a traditional list. It made a numpy.ndarray data type.

numpy.ndarray

<b>Note</b>: ndarray only supports a single data type in it unlike multiple datatypes in the python lists.

In [8]:
try:
    marks = np.array([10, 20, 30])
except ValueError as e:
    print(e)
marks

array(['10', '20', 'hello'], dtype='<U21')

Different ways to create Arrays

In [9]:
#Method 1:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [11]:
# Method 2: From tuples
a = np.array((1, 2, 3))
type(a)

numpy.ndarray

In [13]:
# Method 3: Nested List.
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
print(a)

[[1 2 3]
 [4 5 6]]


Array Properties:

Array properties are among the most frequently used attributes in ML.

1. shape - return the shape of the array. -> (in tuples)
2. ndim - returns the dimension of the array.
3. size - returns the size of the array (rows * columns)
4. dtype - This tells how each element in the array is stored.
5. itemsize - This tell how much space does each element occupies in the array.
6. nbytes - total memory used by the array.

In [14]:
arr = np.array([[1, 2, 3],
                [3, 4, 5],
                [6, 7, 8]])
#shape
print(f"shape of the array: {arr.shape}")
#ndim
print(f"Dimensions of the array: {arr.ndim}")
#size
print(f"Number of elements in the array: {arr.size}")
#dtype
print(f"Elements datatype in the array: {arr.dtype}")
#itemsize
print(f"Size of each element in the array: {arr.itemsize}")
#nbytes
print(f"Total space occupied by the array: {arr.nbytes}")

shape of the array: (3, 3)
Dimensions of the array: 2
Number of elements in the array: 9
Elements datatype in the array: int64
Size of each element in the array: 8
Total space occupied by the array: 72


In [17]:
# Chaning datatypes
arr = arr.astype(np.float64) # np.float64 converts the values to floating points at 64 bit precision.
print(arr)

[[1. 2. 3.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [18]:
# Explicit dtype.
arr = np.array([1, 2, 3], dtype=np.float64) # sets the datatype during the creation of the array.
print(arr)

[1. 2. 3.]


`Importance of Shape in ML`

The most common reason is the matrix multiplication. All the neural network models are just matrix multiplications inside. The simple rule in the matrix multiplication is.

Given a matrix M x N and P x T in order to multiply N == T. if not we raise a shape mismatch error.

So it is compulsory to check the shape of the arrays before proceeding the futher steps.

### Lesson 2: Creating Arrays Like an ML Engineer

Imagine building a neural network. we might need
* Weight matrices
* Bias Vectors
* Identity matrices
* Empty memory for predictions
* Sequences of numbers
* Evenly spaced values

Writing code manually is difficult. Therefore numpy has some helper functions like.

In [22]:
# zeros -> creates an array filled with zeros.
zeros = np.zeros((3, 3), dtype=np.float64)  # default type is float64
print(zeros.shape)
zeros

(3, 3)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# ones
ones = np.ones((2, 2, 3))
print(ones.shape)
ones

(2, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
# full() -> fills the array shape with given value.
fulls = np.full((2, 2), 7)
print(fulls.shape)
fulls

(2, 2)


array([[7, 7],
       [7, 7]])

In [29]:
# empty -> initializes an empty array with already existing bits values in the memory at that location
empty = np.empty((3, 3))
print(empty.shape)
print(empty)

(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#arange -> very similar to range but returns numpy array.
arr = np.arange(start=1, stop=10, step=0.5)
print(arr)
print(type(arr))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
<class 'numpy.ndarray'>


In [34]:
# linspace
arr = np.linspace(0, 10, 5)
print(arr) # linspace cuts values such that it can generate the n numbers.

[ 0.   2.5  5.   7.5 10. ]


In [36]:
# get 1000 values from -pi to +pi
pi = np.linspace(-np.pi, np.pi, 1000)
pi

array([-3.14159265, -3.13530318, -3.1290137 , -3.12272423, -3.11643475,
       -3.11014528, -3.1038558 , -3.09756633, -3.09127686, -3.08498738,
       -3.07869791, -3.07240843, -3.06611896, -3.05982948, -3.05354001,
       -3.04725053, -3.04096106, -3.03467158, -3.02838211, -3.02209263,
       -3.01580316, -3.00951368, -3.00322421, -2.99693473, -2.99064526,
       -2.98435578, -2.97806631, -2.97177683, -2.96548736, -2.95919788,
       -2.95290841, -2.94661894, -2.94032946, -2.93403999, -2.92775051,
       -2.92146104, -2.91517156, -2.90888209, -2.90259261, -2.89630314,
       -2.89001366, -2.88372419, -2.87743471, -2.87114524, -2.86485576,
       -2.85856629, -2.85227681, -2.84598734, -2.83969786, -2.83340839,
       -2.82711891, -2.82082944, -2.81453996, -2.80825049, -2.80196102,
       -2.79567154, -2.78938207, -2.78309259, -2.77680312, -2.77051364,
       -2.76422417, -2.75793469, -2.75164522, -2.74535574, -2.73906627,
       -2.73277679, -2.72648732, -2.72019784, -2.71390837, -2.70

In [41]:
# eye -> creates an identity matrix
idx = np.eye(5)
idx

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
idx = np.identity(4)
idx

# eye v/s identity : eye helps in creating identity matrix in any type but identity returns only square matrices.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
#diag() -> create a diagonal matrix
dia = np.diag((2, 3))
dia

array([[2, 0],
       [0, 3]])

### Lesson 3: Random numbers

In [51]:
# random() -> generates random numbers between 0 and 1
np.random.random([2, 3])

array([[0.13460505, 0.55171702, 0.62338031],
       [0.26853933, 0.11148819, 0.60232638]])

In [54]:
# randint() -> generates a random integer.
np.random.randint(10,size=(2, 3))

array([[3, 1, 6],
       [2, 3, 4]], dtype=int32)

In [55]:
# randn -> instead of generating values between 0 and 1 it generates values using gaussian distribution.
np.random.randn(10, 2)

array([[ 0.11507109,  1.01226861],
       [-0.67672994, -0.27075191],
       [ 0.97437714, -0.09652852],
       [ 0.62031248, -0.09867667],
       [ 0.25800308,  0.11783629],
       [ 0.94560016,  1.02842192],
       [ 1.25452913, -0.24546271],
       [ 1.06607115, -1.40985644],
       [-0.45799824,  0.2418205 ],
       [ 1.19587026, -0.23866993]])

In [56]:
# choice() -> picks a random value from the list.
colors = ["Red", "Green", "Blue"]
np.random.choice(colors)

np.str_('Green')

In [61]:
# shuffle() -> changes the original array.
arr = np.random.randn(2,3)
print(arr)
np.random.shuffle(arr)
print(arr)

[[ 0.54959443 -0.69042372  0.28281822]
 [-1.0486646  -1.71375003 -0.34482021]]
[[ 0.54959443 -0.69042372  0.28281822]
 [-1.0486646  -1.71375003 -0.34482021]]


In [62]:
# permutation() -> makes a new arr instead of modifying it.
new_arr = np.random.permutation(arr)
print(new_arr)

[[-1.0486646  -1.71375003 -0.34482021]
 [ 0.54959443 -0.69042372  0.28281822]]


In [64]:
# seed -> This lets to have a random number and the same value through out the project.

# set seed
np.random.seed(42)
np.random.random(10) # values won't change.

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

### Lesson 4: Fancy indexing, Boolean Indexing.

In [65]:
# sample dataset:
marks = np.array([75, 90, 62, 88, 95, 70, 81, 55])
print(marks)

[75 90 62 88 95 70 81 55]


Fancy Indexing helps in finding the values at the index position.

In [66]:
marks[[1, 2, 5]]

array([90, 62, 70])

In [68]:
#Boolean indexing
marks > 80

array([False,  True, False,  True,  True, False,  True, False])

In [69]:
marks[marks > 80] # can have multiple conditions like this.

array([90, 88, 95, 81])

np.where() : It behaves like if else statement

syntax:<br>
np.where(condition, value_if_true, value_if_false)

In [71]:
result = np.where(
    marks >= 70,
    "Pass",
    "Fail"
)
result

array(['Pass', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass', 'Fail'],
      dtype='<U4')

In [72]:
# The above code helps in replacing the outliers
salary = np.where(
    marks > 90,
    90,
    marks
)
salary

array([75, 90, 62, 88, 90, 70, 81, 55])

### Lesson 5: Reshaping.

In [15]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
# lets try to conver the 1d arr to 2d arr
try:
    mat = arr.reshape(2,4)
    print(mat)
except ValueError as e:
    print(e)

cannot reshape array of size 12 into shape (2,4)


In [17]:
try:
    mat = arr.reshape(5,2)
    print(mat)
except ValueError as e:
    print(e) # Note: Reshape works only if size tallys with the shape we are giving.

cannot reshape array of size 12 into shape (5,2)


In [18]:
# magic of -1
mat = arr.reshape(3, -1)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
mt = arr.reshape(-1, 2)
mt

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
# flatten
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
fla = mat.flatten()
fla # flat creates a new array but ravel stores a view of the values.

array([1, 2, 3, 4, 5, 6])

In [23]:
trans = mat.T
trans

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
# expand_dims()
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np.expand_dims(arr, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

reshape()

1D

↓

2D

-----------------

flatten()

2D

↓

1D (Copy)

-----------------

ravel()

2D

↓

1D (View)

-----------------

expand_dims()

(5,)

↓

(1,5)

-----------------

squeeze()

(1,5,1)

↓

(5,)

### Lesson 6: Broadcasting.

Broadcasting in NumPy is a powerful mechanism that allows arithmetic operations to be performed on arrays of different shapes.

In [29]:
marks = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
marks += 5
marks # No need of loops

array([15, 25, 35, 45, 55, 65, 75, 85, 95])

In [30]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
a + b

array([3, 5, 7])

In [32]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([10,20,30])
a + b

array([[11, 22, 33],
       [14, 25, 36]])

BroadCasting Rules:

1. If the shape of the arrays are same. No problem it executes.
2. If the shape of the array are not same like (3, 4) + (1, 4)  numpy streches the array to become (3, 4)
3. Missing Dimensions are assumed to be 1.

<b>The numpy starts from the rightmost dimension. Always.</b>


Note: `@` is used for matrix multiplication.

In [34]:
a = np.array([
    [1, 2, 3],
    [2, 3, 4]
])
a.shape

(2, 3)

* Scalars can be broadcast across arrays.
* Smaller arrays can behave like larger arrays without copying data.
* Broadcasting compares shapes from right to left.
* A dimension is compatible if it is equal or 1.
* Broadcasting powers image normalization, feature scaling, neural network bias addition, and many other ML operations.

### Lesson 7: Universal Functions and Vectorization.

Universal functions are functions that operates element by element on arrays.

In [40]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [41]:
# addition
a + b

array([3, 5, 7])

In [42]:
# subtraction
a - b

array([-1, -1, -1])

In [43]:
# multiplication
a * b

array([ 2,  6, 12])

In [44]:
# division
a / b

array([0.5       , 0.66666667, 0.75      ])

In [45]:
# power
a ** b

array([ 1,  8, 81])

In [46]:
#absolute value
np.abs(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
#sqrt
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [48]:
#Exponential
np.exp(arr) # e^x .... based on the value at idx

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [49]:
#lop
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [51]:
angles = np.array([0, np.pi, 2 * np.pi])

In [52]:
np.sin(angles)

array([ 0.0000000e+00,  1.2246468e-16, -2.4492936e-16])

In [53]:
np.cos(angles)

array([ 1., -1.,  1.])

In [54]:
arr = np.array([
    2.3,
    5.8,
    9.1
])

In [55]:
np.round(arr)

array([2., 6., 9.])

In [56]:
np.floor(arr)

array([2., 5., 9.])

In [58]:
np.ceil(arr)

array([ 3.,  6., 10.])

In [59]:
arr = np.array([
    -20,
    15,
    90,
    180
])

In [60]:
# clipping gives values only between range from x to y
np.clip(arr,0,100)

array([  0,  15,  90, 100])

In [61]:
def sigmod(x):
    return (1 / (1 + np.exp(-x)))

sigmod(10)

np.float64(0.9999546021312976)

### Lesson 8: Aggregation Functions.


In [62]:
marks = np.array([
    [80, 75, 90],
    [60, 85, 70],
    [95, 88, 92]
])

marks

array([[80, 75, 90],
       [60, 85, 70],
       [95, 88, 92]])

In [64]:
# sum()
marks.sum() # returns the total sum of the elements.

np.int64(735)

In [67]:
#mean() -> returns the mean of the elements
marks.mean()

np.float64(81.66666666666667)

In [68]:
#median() -> returns the median value after sorting
np.median(marks) # sort the array before using it.

np.float64(85.0)

In [69]:
# std() -> returns the standard deviation.
marks.std()

np.float64(10.842303978193728)

In [71]:
# variance() _. returns (std)^2
marks.var()

np.float64(117.55555555555556)

In [72]:
marks.argmax() # returns the index of the largest element in the array

np.int64(6)

In [73]:
# axis

marks.shape

(3, 3)

In [74]:
marks.sum(axis=0)
# imagine axis = 0 -> and axis 1 cols downward arrow.

array([235, 248, 252])

In [75]:
marks.sum(axis=1) # returns the row sum. Remember whatever the axis is represented it is collapsed.

array([245, 215, 275])

In [76]:
A = np.array([
    [2, 0],
    [3, 3]
])

In [77]:
#determinant
np.linalg.det(A)

np.float64(6.0)

In [78]:
np.linalg.matrix_rank(A)

np.int64(2)

In [79]:
values, vectors = np.linalg.eig(A)

In [80]:
print(values, vectors)

[3. 2.] [[ 0.          0.31622777]
 [ 1.         -0.9486833 ]]


### Lesson 9: FILE I/O

In [81]:
marks = np.array([1, 2, 3, 4, 5])
np.save("marks.npy", marks)

In [82]:
loaded = np.load("marks.npy")
print(loaded)

[1 2 3 4 5]


### Helper Functions:

In [83]:
# 1. Min-Max Normalization
import numpy as np
def min_max_scale(x):
    """
    Scale values between 0 and 1
    Formula is x - min(x) / (max(x) - min(x))
    """
    x = np.asarray(x)
    return (x - np.min(x)) / (np.max(x) - np.min(x))

In [ ]:
# 2. Standardization
import numpy as np
def standardize(x):
    """
    mean = 0
    std = 1
    Formula is (x - mean) / (std + eps)
    """
    x = np.asarray(x)
    return ((x - np.mean(x)) / np.std(x))

In [ ]:
# 3. One-Hot Encoding
def one_hot_encoding(labels, num_classes=None):
    labels = np.asarray(labels)
    if num_classes is None:
        num_classes = np.max(labels) + 1

    result = np.zeros((len(labels), num_classes))
    result[np.arange(len(labels)), labels] = 1
    return result

In [84]:
# 4. Accuracy Scores:
def accuracy(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    return np.mean(y_true == y_pred)

In [85]:
# 5. Test-Train-Split
def test_train_split(X, y, test_size=0.2, random_state=42):
    if random_state is not None:
        np.random.seed(random_state)
    indices = np.random.permutation(len(X))
    split = int(len(x) * (1.0 - test_size))
    train_idx = indices[:split]
    test_idx = indices[split:]

    return (
        X[train_idx],
        X[test_idx],
        Y[train_idx],
        Y[test_idx]
    )

In [ ]:
# 6. Confusion Matrix
def confusion_matrix(y_true, y_pred):
    classes = np.unique(
        np.concatenate([y_true, y_pred])
    )
    matrix = np.zeros(
        (len(classes), len(classes)),
        dtype=np.int
    )

    for t, p in zip(y_true, y_pred):
        matrix[t, p] += 1

    return matrix

In [86]:
# 7. Cosine Similarity
def cosine_similarity(a, b):
    a = np.asarray(a)
    b = np.asarray(b)

    return (
        np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
    )

In [87]:
# 8. Sigmod
def sigmod(x):
    return 1 / (1 + np.exp(-x))

In [88]:
# 9. Relu
def relu(x):
    return np.maximum(0, x)

In [90]:
# 10. Softmax
def softmax(x):
    x = np.asarray(x)
    x = x - np.max(x)
    exp = np.exp(x)
    return exp / np.sum(exp)

In [91]:
# 11. Mean Squared Error
def mse(y_true, y_pred):
    return (
        np.mean((y_true - y_pred) ** 2)
    )

In [ ]:
# 12. Binary Cross Entropy
def binary_cross_entropy(y_true, y_pred):
    eps = 1e-15

    y_pred = np.clip(
        y_pred,
        eps,
        1 - eps
    )

    return -np.mean(
        y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)
    )