Pytorch Fundamental

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cu128


In [ ]:
#Introduction to tensors

#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as an it
scalar.item()

7

In [ ]:
#Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix

MATRIX = torch.tensor([[7, 8],
                       [8, 9]])
MATRIX

tensor([[7, 8],
        [8, 9]])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([8, 9])

In [ ]:
MATRIX[1].shape

torch.Size([2])

In [ ]:
#TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [34, 45, 56]],
                       [[5,6,7],
                        [6,7,8],
                        [12, 23, 34]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [34, 45, 56]],

        [[ 5,  6,  7],
         [ 6,  7,  8],
         [12, 23, 34]]])

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[1, 2]

tensor([12, 23, 34])

Random Tensors

Random tensors are important because the way many neural networks learn that they start with tensors full of random numbers and then adjust those weights random numbers to better represent the data

In [ ]:
#create a random tensor

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9362, 0.9565, 0.7434, 0.0290],
        [0.3194, 0.1746, 0.4459, 0.4128],
        [0.7364, 0.5863, 0.7798, 0.1380]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar size of an image

#Gets an error on using to genereate numbers in integers in the rand method

random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor

tensor([[[0.0835, 0.8735, 0.1725],
         [0.8840, 0.5641, 0.2394],
         [0.1367, 0.0859, 0.9006],
         ...,
         [0.0484, 0.6627, 0.8773],
         [0.6851, 0.9143, 0.1385],
         [0.8109, 0.9288, 0.6663]],

        [[0.5808, 0.2412, 0.5326],
         [0.2628, 0.9556, 0.0145],
         [0.2162, 0.7531, 0.9703],
         ...,
         [0.8344, 0.7127, 0.8539],
         [0.4503, 0.4277, 0.9868],
         [0.9714, 0.5065, 0.5435]],

        [[0.4057, 0.6678, 0.8343],
         [0.6650, 0.6594, 0.2744],
         [0.3901, 0.9955, 0.9152],
         ...,
         [0.8085, 0.8291, 0.3182],
         [0.8915, 0.7903, 0.2758],
         [0.0905, 0.1135, 0.5007]],

        ...,

        [[0.7935, 0.9271, 0.0243],
         [0.2445, 0.6576, 0.7408],
         [0.8112, 0.4178, 0.5543],
         ...,
         [0.7425, 0.3578, 0.8460],
         [0.4503, 0.5007, 0.5734],
         [0.3378, 0.4016, 0.3699]],

        [[0.8542, 0.8028, 0.3712],
         [0.3715, 0.3077, 0.8932],
         [0.

In [ ]:
## Zeros and ones

#Float * Int gives Float

zeros = torch.zeros((3, 4), dtype=int)
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4), dtype=float)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [ ]:
#Creating a range of tensors

one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [ ]:
#Creating tensors like

one_to_ten.shape

ten_zeros = torch.zeros_like(one_to_ten)
one_to_ten, ten_zeros


(tensor([1, 3, 5, 7, 9]), tensor([0, 0, 0, 0, 0]))

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 7.0],
                               dtype=torch.float32,  # what the datatype is the tensor...
                               device=None, # what device is the tensor on...
                               requires_grad=False # whether or not to track the gradient of the tensor
                               )
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.int32)
float_16_tensor

tensor([3, 6, 7], dtype=torch.int32)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 49.])

In [ ]:
# Getting info from tensors

some_tensor = torch.rand((3, 4))
some_tensor

tensor([[0.0998, 0.0048, 0.1115, 0.7002],
        [0.7817, 0.1400, 0.1914, 0.4357],
        [0.3671, 0.8136, 0.1808, 0.3829]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.0998, 0.0048, 0.1115, 0.7002],
        [0.7817, 0.1400, 0.1914, 0.4357],
        [0.3671, 0.8136, 0.1808, 0.3829]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply Tensor
tensor = torch.tensor([2, 3, 4])
tensor * 10

tensor([20, 30, 40])

In [ ]:
tensor - 10

tensor([-8, -7, -6])

In [ ]:
torch.mul(tensor, 5)

tensor([10, 15, 20])

In [ ]:
#Elementwise matrix mulitiplication

tensor * tensor

tensor([ 4,  9, 16])

In [ ]:
val = torch.matmul(tensor, tensor) #returns the sum of the product of the elements
val.ndim, val.shape, val

(0, torch.Size([]), tensor(29))

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 909 µs, sys: 0 ns, total: 909 µs
Wall time: 4.09 ms


tensor(29)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 42 µs, sys: 7 µs, total: 49 µs
Wall time: 52 µs


tensor(29)

### one of the most common errors in the deeplearing

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 2))  # (3, 2), (3, 3) throws an error because the inner dimensions the matrix is not same

tensor([[0.3828, 0.2510],
        [0.2990, 0.2222],
        [0.5979, 0.2635]])

In [ ]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[ 7, 10],
                        [ 8, 11],
                        [ 9, 12]])

tensor_B = tensor_B.T #Transpose the tensor

torch.matmul(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, sum etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 2)

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(98), tensor(98))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() # The torch.mean() function requires a tensor of float32 datatype to work

(tensor(49.), tensor(49.))

In [ ]:
torch.sum(x), x.sum()

(tensor(2450), tensor(2450))

In [ ]:
torch.argmax(x).item(), torch.argmin(x.type(torch.float32)).item() # returns the index of the min or max value from the tensor

(49, 0)

### Reshaping, stacking, Squeezing and unSqueezing

In [ ]:
#Reshape the tensor

x = torch.arange(1, 10, 1)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 1, 9)
x_reshaped, x_reshaped.shape

(tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]]), torch.Size([1, 1, 9]))

In [ ]:
#Change the view  (Changing the z changes the x also)

z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#Stack tensors on top of the tensors

#dim = 0 or -2 Gives the stacked tensors in the top
#dim = 1 or -1Creates same col as the row and stacks everything
#dim = -1

x_stacked = torch.stack([x, x, x, x], dim=-2)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#Squeeze the x

x_reshaped.shape

torch.Size([1, 1, 9])

In [ ]:
x_reshaped.shape, x_reshaped.squeeze().shape # remove the 1d

x_squeezed = x_reshaped.squeeze()

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# torch.permute - rearranges the elements of the tensors elements

x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x.permute(2, 0, 1).shape

torch.Size([5, 2, 3])

### Indexing (Selecting data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0] #Gives everything after the first brace

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0, 0] # gives the content from the 2nd brace

tensor([1, 2, 3])

In [ ]:
x[0, 1, 1]

tensor(5)

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
# : to select all the target ele

x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
# Index on x to give 9
x[:, 2, 2]

tensor([9])

In [ ]:
# Index on x to give [3, 6, 9]

x[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch tensors and numpy

In [ ]:
 import numpy as np
 import torch

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # It is not using the same address of the array and it is making a new instance of the tensor
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
#change the value of the array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor
tensor = tensor + 1  # same like the from_numpy() creates a instance of the array and alloactes it to the mem
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

In [ ]:
torch.rand(3, 3)

tensor([[0.9561, 0.4940, 0.3560],
        [0.3057, 0.9306, 0.3715],
        [0.0693, 0.1374, 0.7931]])

In [ ]:
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

tensor_A, tensor_B

(tensor([[0.1668, 0.3480, 0.2389, 0.5922],
         [0.5527, 0.3942, 0.7349, 0.8127],
         [0.5756, 0.8435, 0.7510, 0.8894]]),
 tensor([[0.9394, 0.3558, 0.9524, 0.7360],
         [0.9409, 0.0725, 0.0732, 0.2504],
         [0.3081, 0.1204, 0.3911, 0.3513]]))

In [ ]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)

random_C, random_D, random_C == random_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

### Running tensors or pytorch objects on GPU

In [ ]:
!nvidia-smi

Wed Feb 18 15:49:26 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   66C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
# Check for GPU access fro the pytorch

import torch

torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()


1

In [ ]:
tensor = torch.tensor([1, 2, 3], device="cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_gpu = tensor.to(device)
tensor_gpu.dtype

torch.int64

In [ ]:
#Moving tensor back to cpu

tensor = tensor_gpu.cpu()
print(tensor.dtype)

torch.int64


In [ ]:
# putting tensors and models on gpu

tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')